export interface Country {
  code: string      // ISO 3166-1 alpha-2
  name: string
  dialCode: string
  flag: string
}

const f = (iso: string): string =>
  [...iso.toUpperCase()].map(c => String.fromCodePoint(127397 + c.charCodeAt(0))).join('')

// US first so +1 auto-detects to United States (before Canada)
export const COUNTRIES: Country[] = [
  { code: 'US', name: 'United States',            dialCode: '+1',    flag: f('US') },
  { code: 'AF', name: 'Afghanistan',              dialCode: '+93',   flag: f('AF') },
  { code: 'AL', name: 'Albania',                  dialCode: '+355',  flag: f('AL') },
  { code: 'DZ', name: 'Algeria',                  dialCode: '+213',  flag: f('DZ') },
  { code: 'AR', name: 'Argentina',                dialCode: '+54',   flag: f('AR') },
  { code: 'AM', name: 'Armenia',                  dialCode: '+374',  flag: f('AM') },
  { code: 'AU', name: 'Australia',                dialCode: '+61',   flag: f('AU') },
  { code: 'AT', name: 'Austria',                  dialCode: '+43',   flag: f('AT') },
  { code: 'AZ', name: 'Azerbaijan',               dialCode: '+994',  flag: f('AZ') },
  { code: 'BH', name: 'Bahrain',                  dialCode: '+973',  flag: f('BH') },
  { code: 'BD', name: 'Bangladesh',               dialCode: '+880',  flag: f('BD') },
  { code: 'BY', name: 'Belarus',                  dialCode: '+375',  flag: f('BY') },
  { code: 'BE', name: 'Belgium',                  dialCode: '+32',   flag: f('BE') },
  { code: 'BO', name: 'Bolivia',                  dialCode: '+591',  flag: f('BO') },
  { code: 'BA', name: 'Bosnia and Herzegovina',   dialCode: '+387',  flag: f('BA') },
  { code: 'BR', name: 'Brazil',                   dialCode: '+55',   flag: f('BR') },
  { code: 'BG', name: 'Bulgaria',                 dialCode: '+359',  flag: f('BG') },
  { code: 'KH', name: 'Cambodia',                 dialCode: '+855',  flag: f('KH') },
  { code: 'CA', name: 'Canada',                   dialCode: '+1',    flag: f('CA') },
  { code: 'CL', name: 'Chile',                    dialCode: '+56',   flag: f('CL') },
  { code: 'CN', name: 'China',                    dialCode: '+86',   flag: f('CN') },
  { code: 'CO', name: 'Colombia',                 dialCode: '+57',   flag: f('CO') },
  { code: 'HR', name: 'Croatia',                  dialCode: '+385',  flag: f('HR') },
  { code: 'CU', name: 'Cuba',                     dialCode: '+53',   flag: f('CU') },
  { code: 'CY', name: 'Cyprus',                   dialCode: '+357',  flag: f('CY') },
  { code: 'CZ', name: 'Czech Republic',           dialCode: '+420',  flag: f('CZ') },
  { code: 'DK', name: 'Denmark',                  dialCode: '+45',   flag: f('DK') },
  { code: 'DO', name: 'Dominican Republic',       dialCode: '+1',    flag: f('DO') },
  { code: 'EC', name: 'Ecuador',                  dialCode: '+593',  flag: f('EC') },
  { code: 'EG', name: 'Egypt',                    dialCode: '+20',   flag: f('EG') },
  { code: 'ET', name: 'Ethiopia',                 dialCode: '+251',  flag: f('ET') },
  { code: 'FI', name: 'Finland',                  dialCode: '+358',  flag: f('FI') },
  { code: 'FR', name: 'France',                   dialCode: '+33',   flag: f('FR') },
  { code: 'GE', name: 'Georgia',                  dialCode: '+995',  flag: f('GE') },
  { code: 'DE', name: 'Germany',                  dialCode: '+49',   flag: f('DE') },
  { code: 'GH', name: 'Ghana',                    dialCode: '+233',  flag: f('GH') },
  { code: 'GR', name: 'Greece',                   dialCode: '+30',   flag: f('GR') },
  { code: 'GT', name: 'Guatemala',                dialCode: '+502',  flag: f('GT') },
  { code: 'HK', name: 'Hong Kong',                dialCode: '+852',  flag: f('HK') },
  { code: 'HU', name: 'Hungary',                  dialCode: '+36',   flag: f('HU') },
  { code: 'IS', name: 'Iceland',                  dialCode: '+354',  flag: f('IS') },
  { code: 'IN', name: 'India',                    dialCode: '+91',   flag: f('IN') },
  { code: 'ID', name: 'Indonesia',                dialCode: '+62',   flag: f('ID') },
  { code: 'IR', name: 'Iran',                     dialCode: '+98',   flag: f('IR') },
  { code: 'IQ', name: 'Iraq',                     dialCode: '+964',  flag: f('IQ') },
  { code: 'IE', name: 'Ireland',                  dialCode: '+353',  flag: f('IE') },
  { code: 'IL', name: 'Israel',                   dialCode: '+972',  flag: f('IL') },
  { code: 'IT', name: 'Italy',                    dialCode: '+39',   flag: f('IT') },
  { code: 'JP', name: 'Japan',                    dialCode: '+81',   flag: f('JP') },
  { code: 'JO', name: 'Jordan',                   dialCode: '+962',  flag: f('JO') },
  { code: 'KZ', name: 'Kazakhstan',               dialCode: '+7',    flag: f('KZ') },
  { code: 'KE', name: 'Kenya',                    dialCode: '+254',  flag: f('KE') },
  { code: 'KW', name: 'Kuwait',                   dialCode: '+965',  flag: f('KW') },
  { code: 'LB', name: 'Lebanon',                  dialCode: '+961',  flag: f('LB') },
  { code: 'LT', name: 'Lithuania',                dialCode: '+370',  flag: f('LT') },
  { code: 'LU', name: 'Luxembourg',               dialCode: '+352',  flag: f('LU') },
  { code: 'MY', name: 'Malaysia',                 dialCode: '+60',   flag: f('MY') },
  { code: 'MX', name: 'Mexico',                   dialCode: '+52',   flag: f('MX') },
  { code: 'MA', name: 'Morocco',                  dialCode: '+212',  flag: f('MA') },
  { code: 'NL', name: 'Netherlands',              dialCode: '+31',   flag: f('NL') },
  { code: 'NZ', name: 'New Zealand',              dialCode: '+64',   flag: f('NZ') },
  { code: 'NG', name: 'Nigeria',                  dialCode: '+234',  flag: f('NG') },
  { code: 'NO', name: 'Norway',                   dialCode: '+47',   flag: f('NO') },
  { code: 'OM', name: 'Oman',                     dialCode: '+968',  flag: f('OM') },
  { code: 'PK', name: 'Pakistan',                 dialCode: '+92',   flag: f('PK') },
  { code: 'PE', name: 'Peru',                     dialCode: '+51',   flag: f('PE') },
  { code: 'PH', name: 'Philippines',              dialCode: '+63',   flag: f('PH') },
  { code: 'PL', name: 'Poland',                   dialCode: '+48',   flag: f('PL') },
  { code: 'PT', name: 'Portugal',                 dialCode: '+351',  flag: f('PT') },
  { code: 'QA', name: 'Qatar',                    dialCode: '+974',  flag: f('QA') },
  { code: 'RO', name: 'Romania',                  dialCode: '+40',   flag: f('RO') },
  { code: 'RU', name: 'Russia',                   dialCode: '+7',    flag: f('RU') },
  { code: 'SA', name: 'Saudi Arabia',             dialCode: '+966',  flag: f('SA') },
  { code: 'RS', name: 'Serbia',                   dialCode: '+381',  flag: f('RS') },
  { code: 'SG', name: 'Singapore',                dialCode: '+65',   flag: f('SG') },
  { code: 'SK', name: 'Slovakia',                 dialCode: '+421',  flag: f('SK') },
  { code: 'SI', name: 'Slovenia',                 dialCode: '+386',  flag: f('SI') },
  { code: 'ZA', name: 'South Africa',             dialCode: '+27',   flag: f('ZA') },
  { code: 'KR', name: 'South Korea',              dialCode: '+82',   flag: f('KR') },
  { code: 'ES', name: 'Spain',                    dialCode: '+34',   flag: f('ES') },
  { code: 'LK', name: 'Sri Lanka',                dialCode: '+94',   flag: f('LK') },
  { code: 'SE', name: 'Sweden',                   dialCode: '+46',   flag: f('SE') },
  { code: 'CH', name: 'Switzerland',              dialCode: '+41',   flag: f('CH') },
  { code: 'TW', name: 'Taiwan',                   dialCode: '+886',  flag: f('TW') },
  { code: 'TZ', name: 'Tanzania',                 dialCode: '+255',  flag: f('TZ') },
  { code: 'TH', name: 'Thailand',                 dialCode: '+66',   flag: f('TH') },
  { code: 'TN', name: 'Tunisia',                  dialCode: '+216',  flag: f('TN') },
  { code: 'TR', name: 'Turkey',                   dialCode: '+90',   flag: f('TR') },
  { code: 'UA', name: 'Ukraine',                  dialCode: '+380',  flag: f('UA') },
  { code: 'AE', name: 'United Arab Emirates',     dialCode: '+971',  flag: f('AE') },
  { code: 'GB', name: 'United Kingdom',           dialCode: '+44',   flag: f('GB') },
  { code: 'UY', name: 'Uruguay',                  dialCode: '+598',  flag: f('UY') },
  { code: 'UZ', name: 'Uzbekistan',               dialCode: '+998',  flag: f('UZ') },
  { code: 'VE', name: 'Venezuela',                dialCode: '+58',   flag: f('VE') },
  { code: 'VN', name: 'Vietnam',                  dialCode: '+84',   flag: f('VN') },
  { code: 'YE', name: 'Yemen',                    dialCode: '+967',  flag: f('YE') },
]

// Sorted longest dial code first for unambiguous prefix matching (+380 before +38 before +3)
export const COUNTRIES_BY_DIAL_CODE = [...COUNTRIES].sort(
  (a, b) => b.dialCode.length - a.dialCode.length,
)
