/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as SelectRouteImport } from './routes/select'
import { Route as PhoneNumberInputRouteImport } from './routes/phone-number-input'
import { Route as ModalRouteImport } from './routes/modal'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as InputRouteImport } from './routes/input'
import { Route as GenericContentRouteImport } from './routes/generic-content'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ComboboxRouteImport } from './routes/combobox'
import { Route as CardRouteImport } from './routes/card'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as AccordionRouteImport } from './routes/accordion'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneNumberInputRoute = PhoneNumberInputRouteImport.update({
  id: '/phone-number-input',
  path: '/phone-number-input',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalRoute = ModalRouteImport.update({
  id: '/modal',
  path: '/modal',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const GenericContentRoute = GenericContentRouteImport.update({
  id: '/generic-content',
  path: '/generic-content',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboboxRoute = ComboboxRouteImport.update({
  id: '/combobox',
  path: '/combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionRoute = AccordionRouteImport.update({
  id: '/accordion',
  path: '/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accordion': typeof AccordionRoute
  '/button': typeof ButtonRoute
  '/card': typeof CardRoute
  '/combobox': typeof ComboboxRoute
  '/design': typeof DesignRoute
  '/generic-content': typeof GenericContentRoute
  '/input': typeof InputRoute
  '/layout': typeof LayoutRoute
  '/modal': typeof ModalRoute
  '/phone-number-input': typeof PhoneNumberInputRoute
  '/select': typeof SelectRoute
  '/tokens': typeof TokensRoute
  '/typography': typeof TypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accordion': typeof AccordionRoute
  '/button': typeof ButtonRoute
  '/card': typeof CardRoute
  '/combobox': typeof ComboboxRoute
  '/design': typeof DesignRoute
  '/generic-content': typeof GenericContentRoute
  '/input': typeof InputRoute
  '/layout': typeof LayoutRoute
  '/modal': typeof ModalRoute
  '/phone-number-input': typeof PhoneNumberInputRoute
  '/select': typeof SelectRoute
  '/tokens': typeof TokensRoute
  '/typography': typeof TypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accordion': typeof AccordionRoute
  '/button': typeof ButtonRoute
  '/card': typeof CardRoute
  '/combobox': typeof ComboboxRoute
  '/design': typeof DesignRoute
  '/generic-content': typeof GenericContentRoute
  '/input': typeof InputRoute
  '/layout': typeof LayoutRoute
  '/modal': typeof ModalRoute
  '/phone-number-input': typeof PhoneNumberInputRoute
  '/select': typeof SelectRoute
  '/tokens': typeof TokensRoute
  '/typography': typeof TypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accordion'
    | '/button'
    | '/card'
    | '/combobox'
    | '/design'
    | '/generic-content'
    | '/input'
    | '/layout'
    | '/modal'
    | '/phone-number-input'
    | '/select'
    | '/tokens'
    | '/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accordion'
    | '/button'
    | '/card'
    | '/combobox'
    | '/design'
    | '/generic-content'
    | '/input'
    | '/layout'
    | '/modal'
    | '/phone-number-input'
    | '/select'
    | '/tokens'
    | '/typography'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accordion'
    | '/button'
    | '/card'
    | '/combobox'
    | '/design'
    | '/generic-content'
    | '/input'
    | '/layout'
    | '/modal'
    | '/phone-number-input'
    | '/select'
    | '/tokens'
    | '/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccordionRoute: typeof AccordionRoute
  ButtonRoute: typeof ButtonRoute
  CardRoute: typeof CardRoute
  ComboboxRoute: typeof ComboboxRoute
  DesignRoute: typeof DesignRoute
  GenericContentRoute: typeof GenericContentRoute
  InputRoute: typeof InputRoute
  LayoutRoute: typeof LayoutRoute
  ModalRoute: typeof ModalRoute
  PhoneNumberInputRoute: typeof PhoneNumberInputRoute
  SelectRoute: typeof SelectRoute
  TokensRoute: typeof TokensRoute
  TypographyRoute: typeof TypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-number-input': {
      id: '/phone-number-input'
      path: '/phone-number-input'
      fullPath: '/phone-number-input'
      preLoaderRoute: typeof PhoneNumberInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modal': {
      id: '/modal'
      path: '/modal'
      fullPath: '/modal'
      preLoaderRoute: typeof ModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generic-content': {
      id: '/generic-content'
      path: '/generic-content'
      fullPath: '/generic-content'
      preLoaderRoute: typeof GenericContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combobox': {
      id: '/combobox'
      path: '/combobox'
      fullPath: '/combobox'
      preLoaderRoute: typeof ComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion': {
      id: '/accordion'
      path: '/accordion'
      fullPath: '/accordion'
      preLoaderRoute: typeof AccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccordionRoute: AccordionRoute,
  ButtonRoute: ButtonRoute,
  CardRoute: CardRoute,
  ComboboxRoute: ComboboxRoute,
  DesignRoute: DesignRoute,
  GenericContentRoute: GenericContentRoute,
  InputRoute: InputRoute,
  LayoutRoute: LayoutRoute,
  ModalRoute: ModalRoute,
  PhoneNumberInputRoute: PhoneNumberInputRoute,
  SelectRoute: SelectRoute,
  TokensRoute: TokensRoute,
  TypographyRoute: TypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
