/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InputRouteImport } from './routes/input'
import { Route as GenericContentRouteImport } from './routes/generic-content'
import { Route as CardRouteImport } from './routes/card'
import { Route as ButtonRouteImport } from './routes/button'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const InputRoute = InputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => rootRouteImport,
} as any)
const GenericContentRoute = GenericContentRouteImport.update({
  id: '/generic-content',
  path: '/generic-content',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonRoute = ButtonRouteImport.update({
  id: '/button',
  path: '/button',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/button': typeof ButtonRoute
  '/card': typeof CardRoute
  '/generic-content': typeof GenericContentRoute
  '/input': typeof InputRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/button': typeof ButtonRoute
  '/card': typeof CardRoute
  '/generic-content': typeof GenericContentRoute
  '/input': typeof InputRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/button': typeof ButtonRoute
  '/card': typeof CardRoute
  '/generic-content': typeof GenericContentRoute
  '/input': typeof InputRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/button'
    | '/card'
    | '/generic-content'
    | '/input'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/button' | '/card' | '/generic-content' | '/input'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/button'
    | '/card'
    | '/generic-content'
    | '/input'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ButtonRoute: typeof ButtonRoute
  CardRoute: typeof CardRoute
  GenericContentRoute: typeof GenericContentRoute
  InputRoute: typeof InputRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/input': {
      id: '/input'
      path: '/input'
      fullPath: '/input'
      preLoaderRoute: typeof InputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generic-content': {
      id: '/generic-content'
      path: '/generic-content'
      fullPath: '/generic-content'
      preLoaderRoute: typeof GenericContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button': {
      id: '/button'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ButtonRoute: ButtonRoute,
  CardRoute: CardRoute,
  GenericContentRoute: GenericContentRoute,
  InputRoute: InputRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
